import type { Metadata } from "next"
import Link from "next/link"
import { ArrowLeft, FileText } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms of Service — TOPSEOTOOL",
  description: "Terms of service and fair usage guidelines for TOPSEOTOOL.",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#fafafa] text-neutral-900 py-12 px-4 sm:px-6">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl border border-neutral-200/80 p-8 sm:p-12 shadow-xs">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-xs font-medium text-neutral-500 hover:text-neutral-900 mb-8 transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Back to AI Visibility Tool
        </Link>

        <div className="flex items-center gap-2.5 mb-4">
          <div className="w-8 h-8 rounded-lg bg-blue-50 border border-blue-200 flex items-center justify-center text-blue-600">
            <FileText className="w-4 h-4" />
          </div>
          <span className="text-xs uppercase font-mono font-medium tracking-wider text-neutral-400">
            Terms & Conditions
          </span>
        </div>

        <h1 className="text-3xl font-bold tracking-tight text-neutral-950 mb-3">
          Terms of Service
        </h1>
        <p className="text-sm text-neutral-500 mb-8">
          Last updated: October 2026
        </p>

        <div className="space-y-6 text-sm text-neutral-700 leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing and using TOPSEOTOOL, you agree to comply with and be bound by these terms. If you disagree with any part of these terms, please discontinue using the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-2">2. Acceptable Use</h2>
            <p>
              You agree to use this tool solely to audit public websites for educational, operational, and search optimization purposes. You must not use the tool to crawl private intranet addresses, overload targets with automated denial-of-service traffic, or circumvent security protections.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-2">3. Accuracy of AI Estimates</h2>
            <p>
              AI search rankings and mention assessments are generated by querying real generative models using current web grounding. Generative AI outputs are dynamic and subject to variation. Audit scores and suggestions are provided as strategic guidance without warranty of specific commercial outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-2">4. Intellectual Property & Fair Use</h2>
            <p>
              All code fixes generated by the tool (including llms.txt, JSON-LD, and robots.txt snippets) are provided under public domain / CC0 for you to use freely in your own websites and applications.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
