"use client"

import { useState } from "react"
import { useParams } from "next/navigation"
import {
  Link2, ShieldCheck, ShieldAlert, TrendingUp, Download,
  ExternalLink, Filter, CheckCircle2, AlertTriangle, ArrowUpRight,
  Globe, BarChart3, Search, RefreshCw, FileCode
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { FeatureGate } from "@/components/billing/feature-gate"

interface BacklinkRecord {
  id: string
  sourceTitle: string
  sourceUrl: string
  sourceDr: number
  targetUrl: string
  anchorText: string
  type: "DoFollow" | "NoFollow" | "UGC" | "Sponsored"
  firstSeen: string
  toxicScore: number // 0-100
  status: "Active" | "Lost"
}

const SAMPLE_BACKLINKS: BacklinkRecord[] = [
  {
    id: "b1",
    sourceTitle: "The Comprehensive Guide to Modern Enterprise SEO & Generative Search",
    sourceUrl: "https://searchengineland.com/enterprise-seo-guide-2026",
    sourceDr: 89,
    targetUrl: "https://topseotool.net",
    anchorText: "TopSEOTool enterprise intelligence platform",
    type: "DoFollow",
    firstSeen: "3 days ago",
    toxicScore: 4,
    status: "Active"
  },
  {
    id: "b2",
    sourceTitle: "10 Growth Tools Every Agency Needs in 2026",
    sourceUrl: "https://hubspot.com/blog/agency-growth-tools",
    sourceDr: 93,
    targetUrl: "https://topseotool.net/features",
    anchorText: "best AI search optimization suite",
    type: "DoFollow",
    firstSeen: "1 week ago",
    toxicScore: 2,
    status: "Active"
  },
  {
    id: "b3",
    sourceTitle: "Best Tools for Tracking ChatGPT and Claude Brand Citations",
    sourceUrl: "https://techcrunch.com/2026/02/generative-search-tools",
    sourceDr: 92,
    targetUrl: "https://topseotool.net/ai-perception",
    anchorText: "https://topseotool.net",
    type: "DoFollow",
    firstSeen: "2 weeks ago",
    toxicScore: 1,
    status: "Active"
  },
  {
    id: "b4",
    sourceTitle: "Software Directory & Verified Marketing Reviews",
    sourceUrl: "https://g2.com/products/topseotool/reviews",
    sourceDr: 91,
    targetUrl: "https://topseotool.net",
    anchorText: "visit TopSEOTool",
    type: "NoFollow",
    firstSeen: "1 month ago",
    toxicScore: 3,
    status: "Active"
  },
  {
    id: "b5",
    sourceTitle: "SEO Automated Link Directory #4912 (Suspicious Domain)",
    sourceUrl: "https://free-seo-backlink-farms.biz/links",
    sourceDr: 14,
    targetUrl: "https://topseotool.net/pricing",
    anchorText: "cheap seo software",
    type: "DoFollow",
    firstSeen: "4 days ago",
    toxicScore: 88,
    status: "Active"
  }
]

export default function BacklinksIntelligencePage() {
  const params = useParams()
  const projectId = (params?.projectId as string) || "demo"
  const domain = "topseotool.net"

  const [searchFilter, setSearchFilter] = useState("")
  const [typeFilter, setTypeFilter] = useState<"ALL" | "DoFollow" | "NoFollow" | "Toxic">("ALL")
  const [isRefreshing, setIsRefreshing] = useState(false)

  const filteredLinks = SAMPLE_BACKLINKS.filter((link) => {
    const matchesSearch = link.sourceTitle.toLowerCase().includes(searchFilter.toLowerCase()) ||
      link.sourceUrl.toLowerCase().includes(searchFilter.toLowerCase()) ||
      link.anchorText.toLowerCase().includes(searchFilter.toLowerCase())

    if (!matchesSearch) return false

    if (typeFilter === "DoFollow") return link.type === "DoFollow"
    if (typeFilter === "NoFollow") return link.type === "NoFollow"
    if (typeFilter === "Toxic") return link.toxicScore >= 60

    return true
  })

  const toxicLinksCount = SAMPLE_BACKLINKS.filter(l => l.toxicScore >= 60).length

  const downloadDisavowFile = () => {
    const toxicUrls = SAMPLE_BACKLINKS.filter(l => l.toxicScore >= 60).map(l => `# Toxic link detected\n${l.sourceUrl}`)
    const content = `# Google Disavow File for ${domain}\n# Generated by TopSEOTool\n\n` + toxicUrls.join("\n")
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `disavow_${domain}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div className="p-4 sm:p-6 md:p-8 max-w-7xl mx-auto space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-border/40">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-foreground flex items-center gap-2">
              <Link2 className="h-6 w-6 text-brand" /> Backlink Intelligence & Profile Audit
            </h1>
            <Badge variant="brand" className="text-[10px] font-bold py-0.5">Enterprise</Badge>
          </div>
          <p className="text-xs sm:text-sm text-muted-foreground mt-1">
            Domain Rating, referring domains, anchor distribution, and automated toxic link risk detection
          </p>
        </div>

        <div className="flex items-center gap-2">
          {toxicLinksCount > 0 && (
            <Button
              variant="outline"
              size="sm"
              onClick={downloadDisavowFile}
              className="gap-1.5 text-xs text-red-500 border-red-500/30 hover:bg-red-500/10"
            >
              <FileCode className="h-3.5 w-3.5" /> Export Google Disavow ({toxicLinksCount})
            </Button>
          )}

          <Button
            size="sm"
            onClick={() => { setIsRefreshing(true); setTimeout(() => setIsRefreshing(false), 600); }}
            className="gap-1.5 text-xs bg-brand hover:bg-brand/90 text-brand-foreground"
          >
            <RefreshCw className={`h-3.5 w-3.5 ${isRefreshing ? "animate-spin" : ""}`} /> Refresh Links
          </Button>
        </div>
      </div>

      <FeatureGate feature="backlink_analysis" blurPreview>
        {/* Scorecards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Domain Rating */}
        <Card className="border-border/80 shadow-xs">
          <CardContent className="p-5 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Authority Score (DR)</span>
              <ShieldCheck className="h-4 w-4 text-brand" />
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-black font-mono-nums text-foreground">84</span>
              <span className="text-xs text-muted-foreground">/ 100</span>
              <span className="text-xs font-bold text-emerald-500 ml-auto">+3 pts</span>
            </div>
            <div className="w-full h-1.5 bg-muted rounded-full overflow-hidden">
              <div className="h-full bg-brand rounded-full" style={{ width: "84%" }} />
            </div>
            <p className="text-[10px] text-muted-foreground">Top 2% of websites in your industry</p>
          </CardContent>
        </Card>

        {/* Referring Domains */}
        <Card className="border-border/80 shadow-xs">
          <CardContent className="p-5 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Referring Domains</span>
              <Globe className="h-4 w-4 text-indigo-500" />
            </div>
            <div className="text-3xl font-black font-mono-nums text-foreground">
              1,420
            </div>
            <div className="flex items-center justify-between text-xs text-muted-foreground">
              <span className="text-emerald-500 font-semibold">+18 net new</span>
              <span>88% active</span>
            </div>
          </CardContent>
        </Card>

        {/* Total Backlinks */}
        <Card className="border-border/80 shadow-xs">
          <CardContent className="p-5 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Total Backlinks</span>
              <Link2 className="h-4 w-4 text-emerald-500" />
            </div>
            <div className="text-3xl font-black font-mono-nums text-foreground">
              84,200
            </div>
            <div className="flex items-center justify-between text-xs text-muted-foreground">
              <span className="text-foreground font-semibold">82% DoFollow</span>
              <span>18% NoFollow</span>
            </div>
          </CardContent>
        </Card>

        {/* Toxic Link Risk */}
        <Card className="border-border/80 shadow-xs">
          <CardContent className="p-5 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Toxic Risk Score</span>
              <ShieldAlert className="h-4 w-4 text-emerald-500" />
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-black font-mono-nums text-emerald-500">Low Risk</span>
              <span className="text-xs text-muted-foreground">(2.1%)</span>
            </div>
            <div className="w-full h-1.5 bg-muted rounded-full overflow-hidden">
              <div className="h-full bg-emerald-500 rounded-full" style={{ width: "8%" }} />
            </div>
            <p className="text-[10px] text-muted-foreground">1 suspicious backlink detected for disavow</p>
          </CardContent>
        </Card>
      </div>

      {/* Anchor Text Distribution Overview */}
      <Card className="p-5 border-border/80 shadow-xs space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-bold text-foreground">Top Anchor Text Distribution</h2>
          <span className="text-xs text-muted-foreground">Healthy Natural Ratio</span>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            { label: "Branded Anchors ('topseotool')", pct: 48, count: "40.4K links" },
            { label: "Target Keyword ('ai seo tools')", pct: 24, count: "20.2K links" },
            { label: "Naked URLs ('topseotool.net')", pct: 18, count: "15.1K links" },
            { label: "Generic ('website', 'learn more')", pct: 10, count: "8.4K links" }
          ].map((a) => (
            <div key={a.label} className="p-3 rounded-xl bg-muted/40 border border-border/50 space-y-1.5">
              <div className="flex items-center justify-between text-xs">
                <span className="font-semibold text-foreground truncate">{a.label}</span>
                <span className="font-mono font-bold text-brand">{a.pct}%</span>
              </div>
              <div className="w-full h-1 bg-muted rounded-full overflow-hidden">
                <div className="h-full bg-brand rounded-full" style={{ width: `${a.pct}%` }} />
              </div>
              <span className="text-[10px] text-muted-foreground">{a.count}</span>
            </div>
          ))}
        </div>
      </Card>

      {/* Live Backlink Explorer Table */}
      <Card className="border-border/80 shadow-xs">
        <div className="p-4 sm:p-5 border-b border-border/40 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="relative flex-1 max-w-sm">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
            <Input
              value={searchFilter}
              onChange={(e) => setSearchFilter(e.target.value)}
              placeholder="Search by anchor, source page, or domain..."
              className="pl-8 h-8 text-xs bg-muted/40 border-border/60"
            />
          </div>

          <div className="flex items-center gap-1.5 bg-muted/60 p-1 rounded-xl text-xs font-semibold">
            {(["ALL", "DoFollow", "NoFollow", "Toxic"] as const).map((t) => (
              <button
                key={t}
                onClick={() => setTypeFilter(t)}
                className={`px-3 py-1 rounded-lg transition-all ${
                  typeFilter === t
                    ? "bg-background text-foreground shadow-xs"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                {t === "Toxic" ? `Toxic (${toxicLinksCount})` : t}
              </button>
            ))}
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead className="text-[11px] uppercase tracking-wider text-muted-foreground bg-muted/30 border-b border-border/40">
              <tr>
                <th className="py-3 px-4">Referring Source Page</th>
                <th className="py-3 px-4">Anchor Text & Target</th>
                <th className="py-3 px-4">DR</th>
                <th className="py-3 px-4">Type</th>
                <th className="py-3 px-4">Risk</th>
                <th className="py-3 px-4">First Seen</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/30 font-medium">
              {filteredLinks.map((link) => (
                <tr key={link.id} className="hover:bg-muted/20 transition-colors">
                  <td className="py-3 px-4 max-w-xs sm:max-w-md">
                    <p className="font-semibold text-foreground truncate">{link.sourceTitle}</p>
                    <a
                      href={link.sourceUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[11px] text-muted-foreground hover:text-brand flex items-center gap-1 truncate font-mono mt-0.5"
                    >
                      <span className="truncate">{link.sourceUrl}</span>
                      <ExternalLink className="h-2.5 w-2.5 shrink-0" />
                    </a>
                  </td>

                  <td className="py-3 px-4 max-w-xs">
                    <span className="font-semibold text-foreground inline-block bg-muted/60 px-2 py-0.5 rounded text-[11px] border border-border/50">
                      "{link.anchorText}"
                    </span>
                    <p className="text-[10px] text-muted-foreground font-mono truncate mt-0.5">{link.targetUrl}</p>
                  </td>

                  <td className="py-3 px-4 font-mono font-bold">{link.sourceDr}</td>

                  <td className="py-3 px-4">
                    <Badge variant={link.type === "DoFollow" ? "brand" : "secondary"} className="text-[10px]">
                      {link.type}
                    </Badge>
                  </td>

                  <td className="py-3 px-4">
                    {link.toxicScore >= 60 ? (
                      <Badge variant="outline" className="text-[10px] font-bold border-red-500/40 text-red-500 bg-red-500/10">
                        Toxic ({link.toxicScore}%)
                      </Badge>
                    ) : (
                      <span className="text-emerald-500 font-semibold text-[11px]">Safe</span>
                    )}
                  </td>

                  <td className="py-3 px-4 text-muted-foreground text-[11px]">{link.firstSeen}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
      </FeatureGate>
    </div>
  )
}
